error: Add Incompatible::DirectoryHash
Various hash algorithms are allowed in directory htrees [1], and more
could be added in the future. This error will be used if the library
doesn't know how to handle the algorithm specified in a directory htree
root node.

[1]: https://www.kernel.org/doc/html/latest/filesystems/ext4/globals.html#super-def-hash