error: Mark error types as non_exhaustive
This will allow new error cases to be added in the future without
requiring a change to the semver major version.

https://doc.rust-lang.org/reference/attributes/type_system.html#the-non_exhaustive-attribute