error: Add Incompatible::UnresolvedPath
In the future we'll want to support resolving paths passed to high-level
operations such as `Ext4::read`, meaning that symlinks and '..' get
resolved the same way as in Linux. However, path resolution is somewhat
complicated so for now we'll just return an error if a symlink component
is encountered.

(Symlinks are also a common source of logic and security bugs, so even
when symlink resolution support is added, we might want to add a way to
turn it on/off.)